### PR TITLE
Update Best_Practice_Guide.md

### PR DESCRIPTION
**Pull request by rduerr**
Add standard markup formatting

### CODE REVIEW

**Review by ahayes — APPROVED** [review]
Thanks, Ruth. +1 from me!

**Review by steingod — APPROVED** [review]
Looks good to me.

**Comment by southern-ocean-observing-system** [comment]
Thanks Ruth! I knew it had to be possible to make the text pretty in here because I've seen people do it before.

**Review by southern-ocean-observing-system — APPROVED** [review]

**Comment by rduerr** [comment]
Should we wait for Taco to approve?  Or can we just merge it?

**Comment by ahayes** [comment]
I think we agreed a majority would suffice for significant changes. We could even probably have fewer for typo/formatting pull requests, I imagine.

**Pull request merged**
